datasource:
  jdbc-url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&characterEncoding=UTF-8
  username: root
  password: "duddus186213"
  maximum-pool-size: 10
  connection-timeout: 3000
  validation-timeout: 1000
  max-lifetime: 600000
  connection-test-query: select 1
  data-source-properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    rewriteBatchedStatements: true

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      #temp:
       # use_jdbc_metadata_defaults: false
  generate-ddl: true